/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["acknowledge_v1_alerts__alert_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/{metric}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_v1_analytics__metric__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audits */
        get: operations["audits_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cameras */
        get: operations["cameras_v1_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Camera */
        get: operations["camera_v1_cameras__camera_id__get"];
        /** Configure Camera */
        put: operations["configure_camera_v1_cameras__camera_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_v1_demo_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_v1_demo_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_v1_demo_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/runs/{run_id}/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Control */
        post: operations["control_v1_demo_runs__run_id__control_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_v1_demo_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_v1_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph */
        get: operations["graph_v1_graph_get"];
        /** Configure Edge */
        put: operations["configure_edge_v1_graph_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inputs */
        post: operations["inputs_v1_inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observations */
        get: operations["observations_v1_observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observations/{observation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observation */
        get: operations["observation_v1_observations__observation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observations/{observation_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_v1_observations__observation_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recorded/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recorded Runs */
        get: operations["recorded_runs_v1_recorded_runs_get"];
        put?: never;
        /** Recorded Create */
        post: operations["recorded_create_v1_recorded_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recorded/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recorded Status */
        get: operations["recorded_status_v1_recorded_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recorded/runs/{run_id}/passages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recorded Passages */
        get: operations["recorded_passages_v1_recorded_runs__run_id__passages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recorded/runs/{run_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recorded Replay */
        post: operations["recorded_replay_v1_recorded_runs__run_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recordings */
        get: operations["recordings_v1_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trajectories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trajectories */
        post: operations["trajectories_v1_trajectories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trajectories/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Journey */
        get: operations["journey_v1_trajectories__query_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watches */
        get: operations["watches_v1_watchlists_get"];
        put?: never;
        /** Create Watch */
        post: operations["create_watch_v1_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlists/{watch_id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Watch Action */
        post: operations["watch_action_v1_watchlists__watch_id___action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertData */
        AlertData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Evidence Id */
            evidence_id: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Observation Id */
            observation_id: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "review_required" | "acknowledged";
        } & {
            [key: string]: unknown;
        };
        /** AlertListResponse */
        AlertListResponse: {
            /** Data */
            data: components["schemas"]["AlertData"][];
        };
        /** AnalyticsData */
        AnalyticsData: {
            /** Accepted Plates */
            accepted_plates: number;
            /** Ambiguous Links Excluded */
            ambiguous_links_excluded: number;
            /** Basis */
            basis: string;
            /** Camera Health */
            camera_health: {
                [key: string]: unknown;
            }[];
            /** Counts */
            counts: components["schemas"]["CountData"][];
            /** Flow */
            flow: {
                [key: string]: unknown;
            }[];
            /** Limitations */
            limitations: string[];
            /** Ocr Pending */
            ocr_pending: number;
            /** Od */
            od: {
                [key: string]: unknown;
            }[];
            /** Recognition Coverage */
            recognition_coverage: number | null;
            /** Rejected */
            rejected: number;
            /** Result Version */
            result_version: number;
            /** Review Required */
            review_required: number;
            /** Run Id */
            run_id: string;
            /** Sample Size */
            sample_size: number;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "synthetic" | "recorded_real";
            /**
             * Status
             * @enum {string}
             */
            status: "provisional" | "current_recomputable";
            /** Travel Times */
            travel_times: {
                [key: string]: unknown;
            }[];
            /** Vehicle Passages */
            vehicle_passages: number;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        } & {
            [key: string]: unknown;
        };
        /** AnalyticsResponse */
        AnalyticsResponse: {
            data: components["schemas"]["AnalyticsData"];
        };
        /** CameraConfig */
        CameraConfig: {
            /**
             * Direction
             * @default forward
             * @constant
             */
            direction: "forward";
            /** Name */
            name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Zone Id */
            zone_id: string;
        };
        /** CameraData */
        CameraData: {
            /** Direction */
            direction: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** X */
            x: number | null;
            /** Y */
            y: number | null;
            /** Zone Id */
            zone_id: string | null;
        } & {
            [key: string]: unknown;
        };
        /** CameraListResponse */
        CameraListResponse: {
            /** Data */
            data: components["schemas"]["CameraData"][];
        };
        /** Candidate */
        Candidate: {
            /** Confidence */
            confidence: number;
            /** Text */
            text: string;
        };
        /** ConsensusData */
        ConsensusData: {
            /** Alternatives */
            alternatives: {
                [key: string]: unknown;
            }[];
            /** Contributions */
            contributions: components["schemas"]["Contribution"][];
            /** Independent Frames */
            independent_frames: number;
            /** Margin */
            margin: number;
            /** Plate */
            plate: string | null;
            /** Policy */
            policy: string;
            /** Reasons */
            reasons: string[];
            /** Score */
            score: number;
            /** Score Meaning */
            score_meaning: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "review_required" | "rejected";
            /** Thresholds */
            thresholds: {
                [key: string]: number;
            };
        } & {
            [key: string]: unknown;
        };
        /** Contribution */
        Contribution: {
            /** Frame Id */
            frame_id: string;
            /** Input Score */
            input_score: number;
            /** Normalized */
            normalized: string[];
            /** Raw */
            raw: string;
        } & {
            [key: string]: unknown;
        };
        /** Control */
        Control: {
            /**
             * Action
             * @enum {string}
             */
            action: "play" | "pause" | "step" | "replay" | "retry";
        };
        /** CountData */
        CountData: {
            /** Accepted Plates */
            accepted_plates: number;
            /** Camera Id */
            camera_id: string;
            /** Count Rate Per Minute */
            count_rate_per_minute: number;
            /**
             * Coverage State
             * @enum {string}
             */
            coverage_state: "fresh" | "stale";
            /** Lane Id */
            lane_id: string;
            /** Passages */
            passages: number;
            /** Recognition Coverage */
            recognition_coverage: number | null;
        } & {
            [key: string]: unknown;
        };
        /** Decision */
        Decision: {
            /**
             * Classification
             * @enum {string}
             */
            classification: "true" | "false" | "uncertain";
            /** Notes */
            notes: string;
        };
        /** EdgeConfig */
        EdgeConfig: {
            /** Baseline Seconds */
            baseline_seconds: number;
            /** Distance M */
            distance_m: number;
            /** Max Seconds */
            max_seconds: number;
            /** Min Seconds */
            min_seconds: number;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthData */
        HealthData: {
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** HealthResponse */
        HealthResponse: {
            data: components["schemas"]["HealthData"];
        };
        /** InferredLink */
        InferredLink: {
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /**
             * Observed
             * @constant
             */
            observed: false;
            /** Routes */
            routes: components["schemas"]["Route"][];
            /** Score */
            score: number;
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "plausible" | "ambiguous";
            /** Target */
            target: string;
        } & {
            [key: string]: unknown;
        };
        /** Input */
        Input: {
            /** Camera Id */
            camera_id: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /**
             * Dataset Version
             * @default 1
             * @constant
             */
            dataset_version: "1";
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * Evidence Key
             * @default plate-card.svg
             */
            evidence_key: string;
            /**
             * Inference Origin
             * @default mock_candidates
             * @enum {string}
             */
            inference_origin: "mock_candidates" | "model_inference";
            /**
             * Input Confidence
             * @default 1
             */
            input_confidence: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "passage" | "ocr" | "heartbeat";
            /** Lane Id */
            lane_id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Passage Id */
            passage_id: string;
            /**
             * Quality
             * @default 1
             */
            quality: number;
            /** Readings */
            readings?: components["schemas"]["Reading"][];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /**
             * Source Mode
             * @default synthetic
             * @enum {string}
             */
            source_mode: "synthetic" | "recorded_real";
        };
        /** JourneyData */
        JourneyData: {
            /** Alternatives */
            alternatives: {
                [key: string]: unknown;
            }[];
            /** Id */
            id: string;
            /** Inferred Links */
            inferred_links: components["schemas"]["InferredLink"][];
            /** Limitations */
            limitations: string;
            /** Missing Coverage */
            missing_coverage: {
                [key: string]: unknown;
            }[];
            /** Observed Nodes */
            observed_nodes: components["schemas"]["ObservedNode"][];
            /** Rejected Links */
            rejected_links: components["schemas"]["RejectedLink"][];
            /** Result Version */
            result_version: number;
            /** Review Candidates */
            review_candidates: {
                [key: string]: unknown;
            }[];
            /** Run Id */
            run_id: string;
            /** Scoring Policy */
            scoring_policy: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "synthetic" | "recorded_real";
            /** Truncated */
            truncated: boolean;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        } & {
            [key: string]: unknown;
        };
        /** JourneyResponse */
        JourneyResponse: {
            data: components["schemas"]["JourneyData"];
        };
        /** Login */
        Login: {
            actor: components["schemas"]["Role"];
            /** Password */
            password: string;
        };
        /** ObservationData */
        ObservationData: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Id */
            id: string;
            /**
             * Inference Origin
             * @enum {string}
             */
            inference_origin: "mock_candidates" | "model_inference";
            machine: components["schemas"]["ConsensusData"];
            /** Passage Id */
            passage_id: string;
            /** Plate */
            plate: string | null;
            /** Policy */
            policy: string;
            /**
             * Processed At
             * Format: date-time
             */
            processed_at: string;
            /** Run Id */
            run_id: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "synthetic" | "recorded_real";
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "review_required" | "rejected";
        } & {
            [key: string]: unknown;
        };
        /** ObservationListResponse */
        ObservationListResponse: {
            data: components["schemas"]["ObservationPage"];
        };
        /** ObservationPage */
        ObservationPage: {
            /** Items */
            items: components["schemas"]["ObservedNode"][];
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ObservationResponse */
        ObservationResponse: {
            data: components["schemas"]["ObservationData"];
        };
        /** ObservedNode */
        ObservedNode: {
            /** Camera Id */
            camera_id: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Evidence Id */
            evidence_id: string;
            /** Id */
            id: string;
            /**
             * Inference Origin
             * @enum {string}
             */
            inference_origin: "mock_candidates" | "model_inference";
            /** Lane Id */
            lane_id: string;
            machine: components["schemas"]["ConsensusData"];
            /**
             * Observed
             * @constant
             */
            observed: true;
            /** Passage Id */
            passage_id: string;
            /** Plate */
            plate: string | null;
            /** Policy */
            policy: string;
            /**
             * Processed At
             * Format: date-time
             */
            processed_at: string;
            /** Run Id */
            run_id: string;
            /** Score */
            score: number;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "synthetic" | "recorded_real";
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "review_required" | "rejected";
        } & {
            [key: string]: unknown;
        };
        /** Reading */
        Reading: {
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
            /** Frame Id */
            frame_id: string;
        };
        /** Receipt */
        Receipt: {
            /** Duplicate */
            duplicate: boolean;
            /** Input Id */
            input_id: string;
            /**
             * State
             * @default durably_received
             * @constant
             */
            state: "durably_received";
        };
        /** RejectedLink */
        RejectedLink: {
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /**
             * Observed
             * @constant
             */
            observed: false;
            /** Reason */
            reason: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Result
         * @description Envelope for inspectable domain records; OpenAPI gives stable envelope types.
         */
        Result: {
            /** Data */
            data: {
                [key: string]: unknown;
            } | unknown[];
        };
        /** Review */
        Review: {
            /** Plate */
            plate?: string | null;
            /** Reason */
            reason: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "review_required" | "rejected";
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "viewer" | "investigator" | "administrator" | "approver";
        /** Route */
        Route: {
            /** Baseline Seconds */
            baseline_seconds: number;
            /** Cameras */
            cameras: string[];
            /** Distance M */
            distance_m: number;
        } & {
            [key: string]: unknown;
        };
        /** RunCreate */
        RunCreate: {
            /** Scenario */
            scenario: string;
        };
        /** RunData */
        RunData: {
            /**
             * Clock
             * Format: date-time
             */
            clock: string;
            /** Cursor */
            cursor: number;
            /** Graph */
            graph: {
                [key: string]: unknown;
            }[];
            /** Id */
            id: string;
            /** Scenario */
            scenario: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "synthetic" | "recorded_real";
            /**
             * State
             * @enum {string}
             */
            state: "paused" | "playing" | "delivered";
            /** Version */
            version: number;
        } & {
            [key: string]: unknown;
        };
        /** RunListResponse */
        RunListResponse: {
            /** Data */
            data: components["schemas"]["RunData"][];
        };
        /** RunResponse */
        RunResponse: {
            data: components["schemas"]["RunData"];
        };
        /** TrajectoryQuery */
        TrajectoryQuery: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Include Review
             * @default false
             */
            include_review: boolean;
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /** Plate */
            plate: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoCreate */
        VideoCreate: {
            /**
             * Duration Seconds
             * @default 60
             */
            duration_seconds: number;
            /**
             * Line Y
             * @default 300
             */
            line_y: number;
            /**
             * Recording Id
             * @default delhi_anpr
             * @constant
             */
            recording_id: "delhi_anpr";
            /**
             * Replay Anchor
             * Format: date-time
             * @default 2026-01-01T00:00:00Z
             */
            replay_anchor: string;
            /**
             * Roi Top
             * @default 45
             */
            roi_top: number;
        };
        /** WatchCreate */
        WatchCreate: {
            /** Plate */
            plate: string;
            /** Reason */
            reason: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high";
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alerts_v1_alerts_get: {
        parameters: {
            query: {
                run_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_v1_alerts__alert_id__acknowledge_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_v1_analytics__metric__get: {
        parameters: {
            query: {
                run_id: string;
                start: string;
                end: string;
            };
            header?: never;
            path: {
                metric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audits_v1_audit_get: {
        parameters: {
            query: {
                run_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
        };
    };
    cameras_v1_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraListResponse"];
                };
            };
        };
    };
    camera_v1_cameras__camera_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configure_camera_v1_cameras__camera_id__put: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_v1_demo_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    create_run_v1_demo_runs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_v1_demo_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    control_v1_demo_runs__run_id__control_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Control"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenarios_v1_demo_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
        };
    };
    evidence_v1_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_v1_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
        };
    };
    configure_edge_v1_graph_put: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    inputs_v1_inputs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_v1_jobs_get: {
        parameters: {
            query: {
                run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observations_v1_observations_get: {
        parameters: {
            query: {
                run_id: string;
                start: string;
                end: string;
                plate?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observation_v1_observations__observation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_v1_observations__observation_id__reviews_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Review"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recorded_runs_v1_recorded_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
        };
    };
    recorded_create_v1_recorded_runs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recorded_status_v1_recorded_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recorded_passages_v1_recorded_runs__run_id__passages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recorded_replay_v1_recorded_runs__run_id__replay_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordings_v1_recordings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
        };
    };
    trajectories_v1_trajectories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrajectoryQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    journey_v1_trajectories__query_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watches_v1_watchlists_get: {
        parameters: {
            query: {
                run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watch_v1_watchlists_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watch_action_v1_watchlists__watch_id___action__post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                watch_id: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
