"""initial durable domain schema"""

import sqlalchemy as sa
from alembic import op

revision = "16336384d593"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commands",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor", "operation", "key"),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "local_sessions",
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_table(
        "zones",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cameras",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("dataset_id", sa.String(), nullable=False),
        sa.Column("scenario", sa.String(), nullable=False),
        sa.Column("source_mode", sa.String(), nullable=False),
        sa.Column("network", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("cursor", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("clock", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("graph", sa.JSON(), nullable=False),
        sa.CheckConstraint("source_mode = 'synthetic'"),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("correlation_id", sa.String(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_records_run_id"), "audit_records", ["run_id"], unique=False)
    op.create_table(
        "camera_health",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "camera_id"),
    )
    op.create_table(
        "edges",
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("distance_m", sa.Integer(), nullable=False),
        sa.Column("min_seconds", sa.Integer(), nullable=False),
        sa.Column("max_seconds", sa.Integer(), nullable=False),
        sa.Column("baseline_seconds", sa.Integer(), nullable=False),
        sa.CheckConstraint("distance_m > 0 AND min_seconds > 0 AND max_seconds >= min_seconds"),
        sa.ForeignKeyConstraint(
            ["source"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("source", "target"),
    )
    op.create_table(
        "evidence_assets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column("source_mode", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "object_key"),
    )
    op.create_table(
        "input_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "actor", "key"),
        sa.UniqueConstraint("run_id", "event_id"),
    )
    op.create_index(op.f("ix_input_events_run_id"), "input_events", ["run_id"], unique=False)
    op.create_table(
        "lanes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "camera_id"),
    )
    op.create_table(
        "trajectory_queries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("query", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trajectory_queries_run_id"), "trajectory_queries", ["run_id"], unique=False
    )
    op.create_table(
        "watchlists",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("plate", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("creator", sa.String(), nullable=False),
        sa.Column("approver", sa.String(), nullable=True),
        sa.CheckConstraint("approver IS NULL OR creator <> approver"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_watchlists_run_id"), "watchlists", ["run_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.String(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("state IN ('pending','leased','done','poison')"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["input_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_run_id"), "jobs", ["run_id"], unique=False)
    op.create_index(op.f("ix_jobs_state"), "jobs", ["state"], unique=False)
    op.create_table(
        "vehicle_passages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("passage_key", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column("lane_id", sa.String(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_id", sa.String(), nullable=False),
        sa.Column("evidence_id", sa.String(), nullable=False),
        sa.Column("source_mode", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["input_id"],
            ["input_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lane_id", "camera_id"],
            ["lanes.id", "lanes.camera_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("input_id"),
        sa.UniqueConstraint("run_id", "camera_id", "passage_key"),
    )
    op.create_index(
        "passage_window", "vehicle_passages", ["run_id", "camera_id", "captured_at"], unique=False
    )
    op.create_table(
        "watchlist_approvals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("watchlist_id", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("passage_id", sa.String(), nullable=False),
        sa.Column("input_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("plate", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("machine", sa.JSON(), nullable=False),
        sa.Column("policy", sa.String(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_mode", sa.String(), nullable=False),
        sa.Column("inference_origin", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["input_id"],
            ["input_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["vehicle_passages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("input_id"),
        sa.UniqueConstraint("passage_id"),
    )
    op.create_index("plate_time", "observations", ["run_id", "plate", "captured_at"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("suppression_key", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("observation_id", sa.String(), nullable=True),
        sa.Column("evidence_id", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("suppression_key"),
    )
    op.create_index(op.f("ix_alerts_run_id"), "alerts", ["run_id"], unique=False)
    op.create_table(
        "observation_revisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("observation_id", sa.String(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("plate", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("observation_id", "number"),
    )
    op.create_index(
        op.f("ix_observation_revisions_observation_id"),
        "observation_revisions",
        ["observation_id"],
        unique=False,
    )
    op.create_table(
        "ocr_readings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("observation_id", sa.String(), nullable=False),
        sa.Column("frame_id", sa.String(), nullable=False),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("observation_id", "frame_id"),
    )
    op.create_table(
        "alert_actions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("alert_id", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alert_actions")
    op.drop_table("ocr_readings")
    op.drop_index(
        op.f("ix_observation_revisions_observation_id"), table_name="observation_revisions"
    )
    op.drop_table("observation_revisions")
    op.drop_index(op.f("ix_alerts_run_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("plate_time", table_name="observations")
    op.drop_table("observations")
    op.drop_table("watchlist_approvals")
    op.drop_index("passage_window", table_name="vehicle_passages")
    op.drop_table("vehicle_passages")
    op.drop_index(op.f("ix_jobs_state"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_run_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_watchlists_run_id"), table_name="watchlists")
    op.drop_table("watchlists")
    op.drop_index(op.f("ix_trajectory_queries_run_id"), table_name="trajectory_queries")
    op.drop_table("trajectory_queries")
    op.drop_table("lanes")
    op.drop_index(op.f("ix_input_events_run_id"), table_name="input_events")
    op.drop_table("input_events")
    op.drop_table("evidence_assets")
    op.drop_table("edges")
    op.drop_table("camera_health")
    op.drop_index(op.f("ix_audit_records_run_id"), table_name="audit_records")
    op.drop_table("audit_records")
    op.drop_table("runs")
    op.drop_table("cameras")
    op.drop_table("zones")
    op.drop_table("local_sessions")
    op.drop_table("datasets")
    op.drop_table("commands")
    # ### end Alembic commands ###
